/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Library_Management_System;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class DefaulterList extends javax.swing.JFrame {

    /**
     * Creates new form IssueBookDetails
     */
    DefaultTableModel model;
    Color mouseEnterColor = new Color(102, 255, 51);
    Color mouseExitColor = new Color(0, 102, 0);
    Color mouseCrossEnterColor = new Color(255,51,0);
    Color mouseCrossExitColor = new Color(255, 255, 255);
    Color mouseHomeEnterColor = new Color(255, 51, 51);

    public DefaulterList() {
        initComponents();
        setIssueBookDetailsToTable();
    }

    public void setIssueBookDetailsToTable() {
        long l = System.currentTimeMillis();
        Date todaysDate = new Date(l);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management_system", "root", "gupta22@");
            PreparedStatement pst = con.prepareStatement("select * from issue_book_details where due_date< ? and status = ?");
            pst.setDate(1, todaysDate);
            pst.setString(2, "pending");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                String id = rs.getString("id");
                String bookName = rs.getString("book_name");
                String studentName = rs.getString("student_name");
                String issueDate = rs.getString("issue_date");
                String dueDate = rs.getString("due_date");
                String status = rs.getString("status");

                Object[] obj = {id, bookName, studentName, issueDate, dueDate, status};
                model = (DefaultTableModel) tbl_issuBookDetails.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issuBookDetails = new rojeru_san.complementos.RSTableMetro();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jPanel262 = new javax.swing.JPanel();
        jLabel264 = new javax.swing.JLabel();
        jPanel263 = new javax.swing.JPanel();
        jLabel265 = new javax.swing.JLabel();
        jPanel264 = new javax.swing.JPanel();
        jLabel266 = new javax.swing.JLabel();
        jPanel265 = new javax.swing.JPanel();
        jLabel267 = new javax.swing.JLabel();
        jPanel266 = new javax.swing.JPanel();
        jLabel268 = new javax.swing.JLabel();
        jPanel268 = new javax.swing.JPanel();
        jLabel270 = new javax.swing.JLabel();
        jPanel267 = new javax.swing.JPanel();
        jLabel269 = new javax.swing.JLabel();
        jPanel269 = new javax.swing.JPanel();
        jLabel271 = new javax.swing.JLabel();
        jPanel270 = new javax.swing.JPanel();
        jLabel272 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabel2.setText("     Defaulter List");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 280, 60));

        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/back.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        tbl_issuBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_issuBookDetails.setColorBackgoundHead(new java.awt.Color(255, 51, 0));
        tbl_issuBookDetails.setColorBordeFilas(new java.awt.Color(255, 51, 0));
        tbl_issuBookDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_issuBookDetails.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_issuBookDetails.setColorSelBackgound(new java.awt.Color(102, 255, 51));
        tbl_issuBookDetails.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tbl_issuBookDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        tbl_issuBookDetails.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_issuBookDetails.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_issuBookDetails.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_issuBookDetails.setRowHeight(40);
        tbl_issuBookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_issuBookDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_issuBookDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 890, 300));

        jPanel8.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 350, 4));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 1080, 670));

        jPanel2.setBackground(new java.awt.Color(102, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 5, 35));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel3.setText("Welcome ,Admin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 230, 60));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel4.setText(" Library Management System");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1, 400, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 34));

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/cut.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 40, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(260, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("         Home Page");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 50));

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel5.setForeground(java.awt.Color.lightGray);
        jPanel5.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel6.setText("     Manage Books");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 6, 200, 28));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Features");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, -1));

        jPanel75.setBackground(new java.awt.Color(0, 102, 0));
        jPanel75.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel77.setForeground(java.awt.Color.white);
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel77.setText("       LMS DashBoard");
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel77MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel77MouseExited(evt);
            }
        });
        jPanel75.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, 210, 40));

        jPanel3.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 40));

        jPanel76.setBackground(new java.awt.Color(0, 102, 0));
        jPanel76.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel76MouseEntered(evt);
            }
        });
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel78.setText("    Manage Students");
        jLabel78.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel78MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel78MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel78MouseExited(evt);
            }
        });
        jPanel76.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 210, 28));

        jPanel3.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 40));

        jPanel262.setBackground(new java.awt.Color(0, 102, 0));
        jPanel262.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel262.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel262MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel262MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel262MouseExited(evt);
            }
        });
        jPanel262.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel264.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel264.setForeground(new java.awt.Color(255, 255, 255));
        jLabel264.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel264.setText("     Issue Book");
        jLabel264.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel264MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel264MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel264MouseExited(evt);
            }
        });
        jPanel262.add(jLabel264, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 190, 28));

        jPanel3.add(jPanel262, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 40));

        jPanel263.setBackground(new java.awt.Color(0, 102, 0));
        jPanel263.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel263.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel265.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel265.setForeground(new java.awt.Color(255, 255, 255));
        jLabel265.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        jLabel265.setText("      Return Book");
        jLabel265.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel265MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel265MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel265MouseExited(evt);
            }
        });
        jPanel263.add(jLabel265, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 200, 40));

        jPanel3.add(jPanel263, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 40));

        jPanel264.setBackground(new java.awt.Color(0, 102, 0));
        jPanel264.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel264.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel266.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel266.setForeground(new java.awt.Color(255, 255, 255));
        jLabel266.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel266.setText("     View Records");
        jLabel266.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel266MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel266MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel266MouseExited(evt);
            }
        });
        jPanel264.add(jLabel266, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 200, 40));

        jPanel3.add(jPanel264, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 270, 40));

        jPanel265.setBackground(new java.awt.Color(0, 102, 0));
        jPanel265.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel265.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel267.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel267.setForeground(new java.awt.Color(255, 255, 255));
        jLabel267.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel267.setText("      View Issued Books");
        jLabel267.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel267MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel267MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel267MouseExited(evt);
            }
        });
        jPanel265.add(jLabel267, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 230, 40));

        jPanel3.add(jPanel265, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 270, 40));

        jPanel266.setBackground(new java.awt.Color(0, 102, 0));
        jPanel266.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel266.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel268.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel268.setForeground(new java.awt.Color(255, 255, 255));
        jLabel268.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel268.setText("    View Register Students");
        jLabel268.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel268MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel268MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel268MouseExited(evt);
            }
        });
        jPanel266.add(jLabel268, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 0, 240, 40));

        jPanel268.setBackground(new java.awt.Color(0, 102, 0));
        jPanel268.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel268.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel270.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel270.setForeground(new java.awt.Color(255, 255, 255));
        jLabel270.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel270.setText("      Defaulter List");
        jLabel270.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel270MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel270MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel270MouseExited(evt);
            }
        });
        jPanel268.add(jLabel270, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 188, 40));

        jPanel266.add(jPanel268, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 270, 40));

        jPanel3.add(jPanel266, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 270, 40));

        jPanel267.setBackground(new java.awt.Color(0, 102, 0));
        jPanel267.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel267.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel269.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel269.setForeground(new java.awt.Color(255, 255, 255));
        jLabel269.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Exit_26px.png"))); // NOI18N
        jLabel269.setText("       Logout");
        jLabel269.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel269MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel269MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel269MouseExited(evt);
            }
        });
        jPanel267.add(jLabel269, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 210, 40));

        jPanel3.add(jPanel267, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 270, 50));

        jPanel269.setBackground(new java.awt.Color(0, 102, 0));
        jPanel269.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel269.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel271.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel271.setForeground(new java.awt.Color(255, 255, 255));
        jLabel271.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel271.setText("      Defaulter List");
        jLabel271.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel271MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel271MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel271MouseExited(evt);
            }
        });
        jPanel269.add(jLabel271, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 200, 40));

        jPanel270.setBackground(new java.awt.Color(0, 102, 0));
        jPanel270.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel270.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel272.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel272.setForeground(new java.awt.Color(255, 255, 255));
        jLabel272.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel272.setText("      Defaulter List");
        jLabel272.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel272MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel272MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel272MouseExited(evt);
            }
        });
        jPanel270.add(jLabel272, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 188, 40));

        jPanel269.add(jPanel270, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 270, 40));

        jPanel3.add(jPanel269, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 270, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 270, 670));

        setSize(new java.awt.Dimension(1349, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        HomePage home = new HomePage();
        home.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbl_issuBookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_issuBookDetailsMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_issuBookDetailsMouseClicked

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered

        jButton5.setBackground(mouseCrossEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(mouseCrossExitColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(mouseCrossEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited

        jButton1.setBackground(mouseEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setVisible(false);
        HomePage home = new  HomePage();
        home.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel4.setBackground(mouseCrossEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jPanel4.setBackground(mouseExitColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        setVisible(false);
        ManageBooks books = new ManageBooks();
        books.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered

        jPanel5.setBackground(mouseEnterColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jPanel5.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
        setVisible(false);
        LMSDashBoard lmsdashboard = new  LMSDashBoard();
        lmsdashboard.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel77MouseClicked

    private void jLabel77MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseEntered

        jPanel75.setBackground(mouseEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel77MouseEntered

    private void jLabel77MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseExited

        jPanel75.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel77MouseExited

    private void jLabel78MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseClicked

        setVisible(false);
        ManageStudents  managestudent = new ManageStudents();
        managestudent.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel78MouseClicked

    private void jLabel78MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseEntered

        jPanel76.setBackground(mouseEnterColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel78MouseEntered

    private void jLabel78MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseExited

        jPanel76.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel78MouseExited

    private void jPanel76MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel76MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel76MouseEntered

    private void jLabel264MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel264MouseClicked

        setVisible(false);
        IssueBook book = new IssueBook();
        book.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel264MouseClicked

    private void jLabel264MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel264MouseEntered
        jPanel262.setBackground(mouseEnterColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel264MouseEntered

    private void jLabel264MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel264MouseExited

        jPanel262.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel264MouseExited

    private void jPanel262MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel262MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel262MouseClicked

    private void jPanel262MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel262MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel262MouseEntered

    private void jPanel262MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel262MouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel262MouseExited

    private void jLabel265MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel265MouseClicked

        setVisible(false);
        ReturnBook returnbook = new ReturnBook();
        returnbook.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel265MouseClicked

    private void jLabel265MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel265MouseEntered

        jPanel263.setBackground(mouseEnterColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel265MouseEntered

    private void jLabel265MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel265MouseExited

        jPanel263.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel265MouseExited

    private void jLabel266MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel266MouseClicked

        setVisible(false);
        ViewAllRecord viewallrecord = new  ViewAllRecord();
        viewallrecord.setVisible(true);

    }//GEN-LAST:event_jLabel266MouseClicked

    private void jLabel266MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel266MouseEntered

        jPanel264.setBackground(mouseEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel266MouseEntered

    private void jLabel266MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel266MouseExited

        jPanel264.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel266MouseExited

    private void jLabel267MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel267MouseClicked

        setVisible(false);
        IssueBookDetails issuebookdetails = new  IssueBookDetails();
        issuebookdetails.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel267MouseClicked

    private void jLabel267MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel267MouseEntered

        jPanel265.setBackground(mouseEnterColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel267MouseEntered

    private void jLabel267MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel267MouseExited

        jPanel265.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel267MouseExited

    private void jLabel268MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel268MouseClicked

        setVisible(false);
        RegisterStudents registerstudents = new  RegisterStudents();
        registerstudents.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel268MouseClicked

    private void jLabel268MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel268MouseEntered

        jPanel266.setBackground(mouseEnterColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel268MouseEntered

    private void jLabel268MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel268MouseExited

        jPanel266.setBackground(mouseExitColor);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel268MouseExited

    private void jLabel270MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel270MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel270MouseClicked

    private void jLabel270MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel270MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel270MouseEntered

    private void jLabel270MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel270MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel270MouseExited

    private void jLabel269MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel269MouseClicked

        setVisible(false);
        AdminLogin adminlogin = new  AdminLogin();
        adminlogin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel269MouseClicked

    private void jLabel269MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel269MouseEntered
        jPanel267.setBackground(mouseEnterColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel269MouseEntered

    private void jLabel269MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel269MouseExited
        jPanel267.setBackground(mouseExitColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel269MouseExited

    private void jLabel271MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel271MouseClicked
        setVisible(false);
        DefaulterList defaulterlist = new  DefaulterList();
        defaulterlist.setVisible(true);
             
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel271MouseClicked

    private void jLabel271MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel271MouseEntered
       jPanel269.setBackground(mouseEnterColor);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel271MouseEntered

    private void jLabel271MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel271MouseExited
        jPanel269.setBackground(mouseExitColor); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel271MouseExited

    private void jLabel272MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel272MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel272MouseClicked

    private void jLabel272MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel272MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel272MouseEntered

    private void jLabel272MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel272MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel272MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaulterList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel262;
    private javax.swing.JPanel jPanel263;
    private javax.swing.JPanel jPanel264;
    private javax.swing.JPanel jPanel265;
    private javax.swing.JPanel jPanel266;
    private javax.swing.JPanel jPanel267;
    private javax.swing.JPanel jPanel268;
    private javax.swing.JPanel jPanel269;
    private javax.swing.JPanel jPanel270;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tbl_issuBookDetails;
    // End of variables declaration//GEN-END:variables
}
